document.writeln("<nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("        <div class=\'container-fluid\'> ");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\'");
document.writeln("                    data-target=\'#example-navbar-collapse\'>");
document.writeln("                <span class=\'sr-only\'>切换导航</span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'#\'><strong>小宇商店</strong></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'example-navbar-collapse\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li><a href=\'shouye.html\'><strong>首页</strong></a></li>");
document.writeln("                <li><a href=\'shop.html\'><strong>我的商店</strong></a></li>");
document.writeln("                <li><a href=\'guanyu.html\'><strong>关于我们</strong></a></li>");
document.writeln("                <li><a href=\'connect.html\'><strong>联系我们</strong></a></li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("                        <strong>个人中心</strong><b class=\'caret\'></b>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'#\'><strong>个人信息</strong></a></li>");
document.writeln("                        <li><a href=\'#\'><strong>修改密码</strong></a></li>");
document.writeln("                        <li><a href=\'#\'><strong>消费记录</strong></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("                <li><a href=\'zhuce.html\'><span class=\'glyphicon glyphicon-user\'></span> 注册</a></li>");
document.writeln("                <li><a href=\'loading.html\'><span class=\'glyphicon glyphicon-log-in\'></span> 登录</a></li>");
document.writeln("                <li><a href=\'shopcar.html\'><span class=\'glyphicon glyphicon-shopping-cart\'></span></a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("    </nav>");